### ISSUE TITLE
expose MonitorWidgetFlags?

### ISSUE THREAD

**Issue by leeoniya** [localvoid/perf-monitor#2]
Hey @localvoid ,

Maybe expose `MonitorWidgetFlags` and add a `flags` param to the widgets' apis? This would eliminate need to rebuild the lib to get more compact (or less opinionated) widgets (e.g. hiding graphs, min, max, last).

thanks!

**Comment by localvoid** [comment]
Added new parameter to `startFPSMonitor`, `startMemMonitor` and `initProfiler` to override default MonitorWidgetFlags and exported `MonitorWidgetFlags`.

Here is an example: https://github.com/localvoid/perf-monitor/blob/72e702a195957384f8425a22e53be7c3e39673c5/examples/profile.html#L12-L14

**Comment by leeoniya** [comment]
\o/
