### ISSUE TITLE
Unexpected token: name (MonitorSamplesResult) 

### ISSUE THREAD

**Issue by pablopaul** [localvoid/perf-monitor#3]
Hi, 

when I am trying to make a production build which contains `perf-monitor` via angular-cli 
`ng build --prod`

I get the following error:

```
ERROR in vendor.0586d7976131bc23ba7c.bundle.js from UglifyJs
Unexpected token: name (MonitorSamplesResult) [vendor.0586d7976131bc23ba7c.bundle.js:113243,6]
``` 

Any idea how to solve this?

(Background: I am doing a performance benchmark, this is the reason to include perf-monitor in the `--prod` build)

**Comment by localvoid** [comment]
It seems that angular-cli is using external ES6 modules from `package:module` and doesn't transpile them to ES5. Maybe there is a way to configure it, so it will transpile this module to ES5, or just use ES5 module from `package:main`.

**Comment by pablopaul** [comment]
OK, thank you.

**Comment by pablopaul** [comment]
Do enable the `--prod` temporarily I removed the line 

`"module": "dist/es6/perf-monitor.js",` from perf-monitor´s `package.json` since I did not find a way to configure ángular-cli` to use `package:main`.

**Comment by localvoid** [comment]
Looks like angular is using `es2015` property to specify modules that use es2015 modules and es6 code, `module` for es2015 modules and es5 code, and `main` for umd modules and es5 code.

http://2ality.com/2017/04/setting-up-multi-platform-packages.html#es2015-es6-esm

Haven't seen anyone else to use `es2015` property in `package.json`. But I think that it is good idea, I'll add `es2015` property to `package.json`.
